TRAIN:
  ENABLE: True


  BATCH_SIZE: 10
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True

DATA:
  NUM_FRAMES: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: C:/dataset/UCF101_Label/1

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 50
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.001
  LR_POLICY: steps
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: adam

MODEL:
  NUM_CLASSES: 2

Generator:
  MODEL_NAME: Generator
  LOSS_FUNC: total_G_loss
  INIT_LR: 0.0002
Discriminator:
  MODEL_NAME: Discriminator
  LOSS_FUNC: D_loss
  INIT_LR: 0.00002
  HEAD_ACT: sigmod
  NUM_CLASSES: 2
TEST:
  ENABLE: True
  DATASET: Avenue
  BATCH_SIZE: 10
  CHECKPOINT_FILE_PATH:

DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True

NUM_GPUS: 1
OUTPUT_DIR: F:/ICCV2019_AVENUE
